# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.7'

services:

  db:
    image: docker.io/bitnami/postgresql:15
    container_name: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
#      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRES_USER=toor'
      - 'POSTGRES_PASSWORD=oicu812'
      - 'POSTGRES_DB=mytest_azure'

  vertx:
    container_name: vertx
    #build: .
    #image: skionus/vertx-mid:dev
    image: vertx-mid:dev
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgresql_data:
    driver: local

