services:

  db:
    container_name: postgres
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    # restart: unless-stopped
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_USER=toor
      - POSTGRES_PASSWORD=oicu812
      - POSTGRES_DB=mytest_azure

  vertx:
    container_name: vertx-mid
    # image: skionus/vertx-mid:dev
    image: vertx-mid:dev
    # restart: unless-stopped
    ports:
      - 8080:8080
    # network_mode: "host"
    depends_on:
      - db

  proxy:
    container_name: nginx-proxy
    image: nginx-proxy:dev
    ports:
      - 80:80
      - 443:443
    # restart: unless-stopped
    depends_on:
      - vertx
    volumes:
      - ../nginx-proxy/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../nginx-proxy/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ../nginx-proxy/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key

  # nginx-react:
  #   container_name: react-admin-nginx
  #   image: react-admin-nginx:dev
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000

volumes:
  postgresql_data:
    driver: local

